[2025-02-17T19:08:34.269+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:08:34.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:08:34.272+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:08:34.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:08:34.317+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:08:34.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:08:34.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:08:34.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.066 seconds
[2025-02-17T19:09:05.192+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:09:05.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:09:05.194+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:09:05.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:09:05.212+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:09:05.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:09:05.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:09:05.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:09:35.843+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:09:35.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:09:35.845+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:09:35.845+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:09:35.870+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:09:35.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:09:35.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:09:35.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.040 seconds
[2025-02-17T19:10:06.137+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:10:06.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:10:06.139+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:10:06.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:10:06.156+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:10:06.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:10:06.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:10:06.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T19:10:36.552+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:10:36.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:10:36.554+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:10:36.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:10:36.573+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:10:36.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:10:36.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:10:36.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T19:11:06.702+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:11:06.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:11:06.704+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:11:06.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:11:06.721+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:11:06.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:11:06.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:11:06.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:11:36.925+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:11:36.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:11:36.928+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:11:36.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:11:36.947+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:11:36.944+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:11:36.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:11:36.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.036 seconds
[2025-02-17T19:12:07.466+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:12:07.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:12:07.468+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:12:07.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:12:07.488+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:12:07.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:12:07.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:12:07.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.036 seconds
[2025-02-17T19:12:37.910+0000] {processor.py:186} INFO - Started process (PID=547) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:12:37.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:12:37.912+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:12:37.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:12:37.929+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:12:37.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:12:37.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:12:37.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:13:08.220+0000] {processor.py:186} INFO - Started process (PID=611) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:13:08.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:13:08.222+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:13:08.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:13:08.239+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:13:08.237+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:13:08.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:13:08.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:13:38.539+0000] {processor.py:186} INFO - Started process (PID=675) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:13:38.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:13:38.541+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:13:38.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:13:38.560+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:13:38.556+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:13:38.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:13:38.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T19:14:08.878+0000] {processor.py:186} INFO - Started process (PID=739) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:14:08.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:14:08.880+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:08.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:14:08.898+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:08.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:14:08.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:14:08.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:14:39.303+0000] {processor.py:186} INFO - Started process (PID=803) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:14:39.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:14:39.307+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:39.306+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:14:39.325+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:39.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:14:39.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:14:39.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T19:15:09.715+0000] {processor.py:186} INFO - Started process (PID=867) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:15:09.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:15:09.718+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:09.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:15:09.735+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:09.732+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:15:09.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:15:09.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:15:40.680+0000] {processor.py:186} INFO - Started process (PID=931) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:15:40.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:15:40.682+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:40.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:15:40.699+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:40.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:15:40.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:15:40.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:16:10.938+0000] {processor.py:186} INFO - Started process (PID=995) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:16:10.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:16:10.941+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:10.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:16:10.958+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:10.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:16:10.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:16:10.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T19:16:41.424+0000] {processor.py:186} INFO - Started process (PID=1059) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:16:41.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:16:41.426+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:41.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:16:41.445+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:41.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:16:41.447+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:16:41.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T19:17:11.485+0000] {processor.py:186} INFO - Started process (PID=1123) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:17:11.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:17:11.487+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:11.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:17:11.506+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:11.503+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:17:11.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:17:11.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.035 seconds
[2025-02-17T19:17:41.761+0000] {processor.py:186} INFO - Started process (PID=1187) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:17:41.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:17:41.764+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:41.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:17:41.783+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:41.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:17:41.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:17:41.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.035 seconds
[2025-02-17T19:18:12.602+0000] {processor.py:186} INFO - Started process (PID=1252) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:18:12.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:18:12.605+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:12.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:18:12.624+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:12.621+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:18:12.625+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:18:12.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T19:18:43.507+0000] {processor.py:186} INFO - Started process (PID=1316) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:18:43.508+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:18:43.510+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:43.510+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:18:43.528+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:43.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:18:43.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:18:43.537+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T19:19:14.287+0000] {processor.py:186} INFO - Started process (PID=1380) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:19:14.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:19:14.290+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:14.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:19:14.315+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:14.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:19:14.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:19:14.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.046 seconds
[2025-02-17T19:19:44.798+0000] {processor.py:186} INFO - Started process (PID=1444) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:19:44.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:19:44.800+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:44.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:19:44.818+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:44.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:19:44.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:19:44.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.036 seconds
[2025-02-17T19:20:15.755+0000] {processor.py:186} INFO - Started process (PID=1508) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:20:15.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:20:15.757+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:15.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:20:15.775+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:15.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:20:15.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:20:15.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T19:20:46.047+0000] {processor.py:186} INFO - Started process (PID=1572) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:20:46.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:20:46.049+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:46.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:20:46.065+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:46.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:20:46.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:20:46.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:21:16.291+0000] {processor.py:186} INFO - Started process (PID=1637) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:21:16.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:21:16.293+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:16.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:21:16.309+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:16.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:21:16.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:21:16.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:21:46.699+0000] {processor.py:186} INFO - Started process (PID=1701) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:21:46.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:21:46.702+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:46.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:21:46.717+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:46.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:21:46.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:21:46.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:22:17.113+0000] {processor.py:186} INFO - Started process (PID=1765) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:22:17.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:22:17.116+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:17.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:22:17.133+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:17.131+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:22:17.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:22:17.142+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:22:47.523+0000] {processor.py:186} INFO - Started process (PID=1829) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:22:47.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:22:47.525+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:47.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:22:47.545+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:47.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:22:47.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:22:47.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T19:23:17.989+0000] {processor.py:186} INFO - Started process (PID=1899) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:23:17.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:23:17.992+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:17.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:23:18.012+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:18.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:23:18.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:23:18.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.039 seconds
[2025-02-17T19:23:48.568+0000] {processor.py:186} INFO - Started process (PID=1963) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:23:48.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:23:48.571+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:48.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:23:48.588+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:48.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:23:48.589+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:23:48.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:24:18.847+0000] {processor.py:186} INFO - Started process (PID=2027) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:24:18.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:24:18.850+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:24:18.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:24:18.867+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:24:18.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:24:18.868+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:24:18.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.035 seconds
[2025-02-17T19:24:49.571+0000] {processor.py:186} INFO - Started process (PID=2091) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:24:49.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:24:49.573+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:24:49.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:24:49.591+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:24:49.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:24:49.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:24:49.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:25:20.364+0000] {processor.py:186} INFO - Started process (PID=2155) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:25:20.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:25:20.367+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:25:20.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:25:20.384+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:25:20.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:25:20.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:25:20.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:25:50.804+0000] {processor.py:186} INFO - Started process (PID=2219) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:25:50.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:25:50.807+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:25:50.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:25:50.823+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:25:50.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:25:50.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:25:50.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:26:21.243+0000] {processor.py:186} INFO - Started process (PID=2283) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:26:21.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:26:21.245+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:26:21.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:26:21.261+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:26:21.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:26:21.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:26:21.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:26:51.455+0000] {processor.py:186} INFO - Started process (PID=2347) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:26:51.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:26:51.457+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:26:51.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:26:51.473+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:26:51.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:26:51.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:26:51.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:27:21.734+0000] {processor.py:186} INFO - Started process (PID=2411) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:27:21.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:27:21.737+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:27:21.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:27:21.753+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:27:21.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:27:21.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:27:21.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:27:51.999+0000] {processor.py:186} INFO - Started process (PID=2475) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:27:52.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:27:52.002+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:27:52.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:27:52.019+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:27:52.017+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:27:52.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:27:52.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:28:22.264+0000] {processor.py:186} INFO - Started process (PID=2539) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:28:22.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:28:22.267+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:28:22.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:28:22.283+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:28:22.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:28:22.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:28:22.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:28:52.523+0000] {processor.py:186} INFO - Started process (PID=2603) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:28:52.523+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:28:52.525+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:28:52.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:28:52.541+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:28:52.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:28:52.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:28:52.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:29:22.800+0000] {processor.py:186} INFO - Started process (PID=2667) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:29:22.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:29:22.803+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:29:22.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:29:22.823+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:29:22.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:29:22.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:29:22.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T19:29:53.037+0000] {processor.py:186} INFO - Started process (PID=2731) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:29:53.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:29:53.039+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:29:53.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:29:53.055+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:29:53.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:29:53.056+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:29:53.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.030 seconds
[2025-02-17T19:30:24.064+0000] {processor.py:186} INFO - Started process (PID=2788) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:30:24.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:30:24.066+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:30:24.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:30:24.083+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:30:24.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:30:24.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:30:24.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:30:54.581+0000] {processor.py:186} INFO - Started process (PID=2850) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:30:54.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:30:54.584+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:30:54.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:30:54.602+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:30:54.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:30:54.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:30:54.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.035 seconds
[2025-02-17T19:31:25.671+0000] {processor.py:186} INFO - Started process (PID=2913) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:31:25.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:31:25.674+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:31:25.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:31:25.690+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:31:25.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:31:25.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:31:25.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:31:55.847+0000] {processor.py:186} INFO - Started process (PID=2962) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:31:55.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:31:55.849+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:31:55.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:31:55.868+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:31:55.865+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:31:55.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:31:55.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.036 seconds
[2025-02-17T19:32:26.615+0000] {processor.py:186} INFO - Started process (PID=3026) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:32:26.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:32:26.617+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:32:26.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:32:26.634+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:32:26.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:32:26.635+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:32:26.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:32:57.162+0000] {processor.py:186} INFO - Started process (PID=3090) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:32:57.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:32:57.164+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:32:57.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:32:57.182+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:32:57.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:32:57.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:32:57.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T19:33:27.828+0000] {processor.py:186} INFO - Started process (PID=3154) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:33:27.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:33:27.830+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:33:27.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:33:27.846+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:33:27.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:33:27.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:33:27.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.030 seconds
[2025-02-17T19:33:58.538+0000] {processor.py:186} INFO - Started process (PID=3218) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:33:58.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:33:58.540+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:33:58.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:33:58.557+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:33:58.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:33:58.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:33:58.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:34:29.186+0000] {processor.py:186} INFO - Started process (PID=3283) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:34:29.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:34:29.188+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:34:29.188+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:34:29.206+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:34:29.204+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:34:29.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:34:29.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:34:59.554+0000] {processor.py:186} INFO - Started process (PID=3347) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:34:59.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:34:59.556+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:34:59.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:34:59.573+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:34:59.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:34:59.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:34:59.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:35:30.124+0000] {processor.py:186} INFO - Started process (PID=3411) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:35:30.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:35:30.126+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:35:30.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:35:30.145+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:35:30.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:35:30.146+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:35:30.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.035 seconds
[2025-02-17T19:36:00.850+0000] {processor.py:186} INFO - Started process (PID=3473) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:36:00.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:36:00.852+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:36:00.852+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:36:00.868+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:36:00.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:36:00.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:36:00.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:36:31.415+0000] {processor.py:186} INFO - Started process (PID=3537) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:36:31.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:36:31.418+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:36:31.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:36:31.434+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:36:31.432+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:36:31.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:36:31.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:37:02.041+0000] {processor.py:186} INFO - Started process (PID=3601) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:37:02.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:37:02.048+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:37:02.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:37:02.067+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:37:02.064+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:37:02.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:37:02.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.041 seconds
[2025-02-17T19:37:32.711+0000] {processor.py:186} INFO - Started process (PID=3665) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:37:32.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:37:32.714+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:37:32.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:37:32.730+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:37:32.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:37:32.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:37:32.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T19:42:23.036+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:42:23.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:42:23.039+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:42:23.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:42:23.094+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:42:23.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:42:23.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:42:23.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.080 seconds
[2025-02-17T19:42:53.311+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:42:53.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:42:53.314+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:42:53.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:42:53.333+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:42:53.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:42:53.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:42:53.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.035 seconds
[2025-02-17T19:43:23.624+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:43:23.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:43:23.627+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:43:23.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:43:23.649+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:43:23.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:43:23.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:43:23.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.038 seconds
[2025-02-17T19:43:54.152+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:43:54.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:43:54.155+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:43:54.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:43:54.177+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:43:54.174+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:43:54.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:43:54.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.041 seconds
[2025-02-17T19:44:24.377+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:44:24.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:44:24.379+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:44:24.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:44:24.397+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:44:24.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:44:24.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:44:24.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.035 seconds
[2025-02-17T19:44:54.953+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:44:54.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:44:54.956+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:44:54.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:44:54.972+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:44:54.970+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:44:54.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:44:54.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T19:45:25.437+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:45:25.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:45:25.440+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:45:25.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:45:25.457+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:45:25.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:45:25.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:45:25.465+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T19:45:56.078+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:45:56.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:45:56.081+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:45:56.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:45:56.102+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:45:56.099+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:45:56.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:45:56.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.040 seconds
[2025-02-17T19:46:26.525+0000] {processor.py:186} INFO - Started process (PID=547) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:46:26.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T19:46:26.528+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:46:26.528+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:46:26.548+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:46:26.545+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T19:46:26.550+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T19:46:26.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.040 seconds
[2025-02-17T20:00:05.416+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:00:05.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:00:05.422+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:00:05.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:00:05.487+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:00:05.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:00:05.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:00:05.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.091 seconds
[2025-02-17T20:00:35.999+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:00:36.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:00:36.004+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:00:36.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:00:36.028+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:00:36.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:00:36.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:00:36.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.045 seconds
[2025-02-17T20:01:06.220+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:01:06.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:01:06.223+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:01:06.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:01:06.251+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:01:06.246+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:01:06.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:01:06.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.050 seconds
[2025-02-17T20:01:36.461+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:01:36.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:01:36.464+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:01:36.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:01:36.485+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:01:36.481+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:01:36.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:01:36.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.041 seconds
[2025-02-17T20:02:06.623+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:02:06.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:02:06.626+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:02:06.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:02:06.645+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:02:06.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:02:06.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:02:06.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T20:02:37.104+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:02:37.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:02:37.106+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:02:37.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:02:37.128+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:02:37.125+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:02:37.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:02:37.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.041 seconds
[2025-02-17T20:03:07.464+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:03:07.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:03:07.467+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:03:07.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:03:07.488+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:03:07.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:03:07.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:03:07.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.040 seconds
[2025-02-17T20:03:37.660+0000] {processor.py:186} INFO - Started process (PID=484) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:03:37.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:03:37.664+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:03:37.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:03:37.687+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:03:37.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:03:37.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:03:37.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.046 seconds
[2025-02-17T20:04:07.748+0000] {processor.py:186} INFO - Started process (PID=548) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:04:07.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:04:07.751+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:04:07.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:04:07.768+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:04:07.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:04:07.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:04:07.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T20:04:37.824+0000] {processor.py:186} INFO - Started process (PID=612) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:04:37.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:04:37.827+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:04:37.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:04:37.844+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:04:37.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:04:37.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:04:37.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T20:05:08.038+0000] {processor.py:186} INFO - Started process (PID=676) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:05:08.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:05:08.041+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:05:08.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:05:08.069+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:05:08.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:05:08.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:05:08.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.049 seconds
[2025-02-17T20:05:38.353+0000] {processor.py:186} INFO - Started process (PID=740) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:05:38.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:05:38.356+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:05:38.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:05:38.377+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:05:38.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:05:38.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:05:38.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.040 seconds
[2025-02-17T20:06:09.099+0000] {processor.py:186} INFO - Started process (PID=804) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:06:09.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:06:09.101+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:06:09.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:06:09.118+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:06:09.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:06:09.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:06:09.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T20:06:39.545+0000] {processor.py:186} INFO - Started process (PID=868) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:06:39.546+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:06:39.548+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:06:39.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:06:39.566+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:06:39.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:06:39.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:06:39.576+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.035 seconds
[2025-02-17T20:07:09.808+0000] {processor.py:186} INFO - Started process (PID=932) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:07:09.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:07:09.810+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:07:09.810+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:07:09.827+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:07:09.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:07:09.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:07:09.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.031 seconds
[2025-02-17T20:07:40.772+0000] {processor.py:186} INFO - Started process (PID=996) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:07:40.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:07:40.774+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:07:40.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:07:40.793+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:07:40.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:07:40.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:07:40.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T20:08:10.898+0000] {processor.py:186} INFO - Started process (PID=1060) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:08:10.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:08:10.900+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:08:10.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:08:10.917+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:08:10.914+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:08:10.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:08:10.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T20:08:41.793+0000] {processor.py:186} INFO - Started process (PID=1124) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:08:41.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:08:41.795+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:08:41.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:08:41.813+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:08:41.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:08:41.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:08:41.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T20:09:11.911+0000] {processor.py:186} INFO - Started process (PID=1188) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:09:11.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:09:11.913+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:09:11.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:09:11.931+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:09:11.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:09:11.932+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:09:11.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T20:09:41.968+0000] {processor.py:186} INFO - Started process (PID=1252) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:09:41.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:09:41.971+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:09:41.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:09:41.988+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:09:41.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:09:41.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:09:41.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T20:10:12.047+0000] {processor.py:186} INFO - Started process (PID=1316) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:10:12.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:10:12.049+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:10:12.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:10:12.066+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:10:12.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:10:12.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:10:12.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.032 seconds
[2025-02-17T20:10:42.310+0000] {processor.py:186} INFO - Started process (PID=1380) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:10:42.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:10:42.313+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:10:42.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:10:42.336+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:10:42.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:10:42.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:10:42.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.046 seconds
[2025-02-17T20:11:13.110+0000] {processor.py:186} INFO - Started process (PID=1444) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:11:13.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:11:13.115+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:11:13.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:11:13.136+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:11:13.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:11:13.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:11:13.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.042 seconds
[2025-02-17T20:11:43.874+0000] {processor.py:186} INFO - Started process (PID=1508) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:11:43.876+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:11:43.878+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:11:43.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:11:43.900+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:11:43.897+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:11:43.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:11:43.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.041 seconds
[2025-02-17T20:12:14.166+0000] {processor.py:186} INFO - Started process (PID=1572) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:12:14.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:12:14.168+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:12:14.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:12:14.186+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:12:14.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:12:14.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:12:14.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T20:12:44.606+0000] {processor.py:186} INFO - Started process (PID=1636) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:12:44.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:12:44.608+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:12:44.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:12:44.629+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:12:44.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:12:44.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:12:44.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.038 seconds
[2025-02-17T20:13:14.768+0000] {processor.py:186} INFO - Started process (PID=1700) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:13:14.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:13:14.770+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:13:14.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:13:14.790+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:13:14.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:13:14.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:13:14.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.036 seconds
[2025-02-17T20:13:44.992+0000] {processor.py:186} INFO - Started process (PID=1764) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:13:44.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:13:44.994+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:13:44.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:13:45.013+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:13:45.011+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:13:45.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:13:45.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.036 seconds
[2025-02-17T20:14:15.282+0000] {processor.py:186} INFO - Started process (PID=1828) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:14:15.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:14:15.284+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:14:15.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:14:15.302+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:14:15.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:14:15.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:14:15.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T20:14:45.487+0000] {processor.py:186} INFO - Started process (PID=1892) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:14:45.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:14:45.489+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:14:45.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:14:45.507+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:14:45.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:14:45.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:14:45.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T20:15:15.824+0000] {processor.py:186} INFO - Started process (PID=1956) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:15:15.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:15:15.827+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:15:15.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:15:15.844+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:15:15.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:15:15.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:15:15.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.033 seconds
[2025-02-17T20:15:46.136+0000] {processor.py:186} INFO - Started process (PID=2020) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:15:46.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:15:46.138+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:15:46.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:15:46.156+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:15:46.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:15:46.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:15:46.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T20:16:16.712+0000] {processor.py:186} INFO - Started process (PID=2084) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:16:16.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:16:16.715+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:16:16.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:16:16.734+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:16:16.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:16:16.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:16:16.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.036 seconds
[2025-02-17T20:16:47.543+0000] {processor.py:186} INFO - Started process (PID=2154) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:16:47.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:16:47.546+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:16:47.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:16:47.566+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:16:47.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:16:47.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:16:47.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.036 seconds
[2025-02-17T20:17:17.890+0000] {processor.py:186} INFO - Started process (PID=2218) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:17:17.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:17:17.893+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:17:17.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:17:17.911+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:17:17.908+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:17:17.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:17:17.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T20:17:48.379+0000] {processor.py:186} INFO - Started process (PID=2282) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:17:48.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:17:48.383+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:17:48.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:17:48.401+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:17:48.398+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:17:48.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:17:48.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.036 seconds
[2025-02-17T20:18:19.851+0000] {processor.py:186} INFO - Started process (PID=2346) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:18:19.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:18:19.854+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:18:19.854+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:18:19.874+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:18:19.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:18:19.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:18:19.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T20:18:49.960+0000] {processor.py:186} INFO - Started process (PID=2392) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:18:49.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:18:49.963+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:18:49.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:18:49.982+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:18:49.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:18:49.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:18:49.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.038 seconds
[2025-02-17T20:19:20.729+0000] {processor.py:186} INFO - Started process (PID=2454) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:19:20.730+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:19:20.732+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:19:20.731+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:19:20.751+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:19:20.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:19:20.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:19:20.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T20:19:51.032+0000] {processor.py:186} INFO - Started process (PID=2508) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:19:51.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:19:51.035+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:19:51.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:19:51.053+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:19:51.051+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:19:51.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:19:51.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T20:20:21.293+0000] {processor.py:186} INFO - Started process (PID=2572) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:20:21.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:20:21.297+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:20:21.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:20:21.318+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:20:21.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:20:21.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:20:21.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.040 seconds
[2025-02-17T20:20:52.136+0000] {processor.py:186} INFO - Started process (PID=2634) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:20:52.137+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:20:52.139+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:20:52.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:20:52.160+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:20:52.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:20:52.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:20:52.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.040 seconds
[2025-02-17T20:21:22.581+0000] {processor.py:186} INFO - Started process (PID=2698) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:21:22.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:21:22.584+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:21:22.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:21:22.607+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:21:22.604+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:21:22.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:21:22.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.040 seconds
[2025-02-17T20:21:53.392+0000] {processor.py:186} INFO - Started process (PID=2762) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:21:53.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:21:53.413+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:21:53.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:21:53.437+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:21:53.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:21:53.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:21:54.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 1.311 seconds
[2025-02-17T20:22:25.635+0000] {processor.py:186} INFO - Started process (PID=2826) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:22:25.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:22:25.638+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:22:25.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:22:25.655+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:22:25.653+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:22:25.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:22:25.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.034 seconds
[2025-02-17T20:22:55.900+0000] {processor.py:186} INFO - Started process (PID=2890) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:22:55.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:22:55.903+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:22:55.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:22:55.922+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:22:55.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:22:55.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:22:55.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.037 seconds
[2025-02-17T20:23:26.055+0000] {processor.py:186} INFO - Started process (PID=2954) to work on /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:23:26.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_to_staging.py for tasks to queue
[2025-02-17T20:23:26.058+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:23:26.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:23:26.077+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:23:26.074+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/load_to_staging.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_staging.py", line 16, in <module>
    'host': Variable.get('postgres_host'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable postgres_host does not exist'
[2025-02-17T20:23:26.079+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_staging.py
[2025-02-17T20:23:26.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_to_staging.py took 0.038 seconds
